title: Derelle Kirksey # your name (or website title) here
logo: "/images/DK-Symbol.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>An experienced engineering professional with process design/improvement experience at a fast-paced public bio-technology company. Expertise in automation, process engineering, data analysis, and working with diversified teams. Polished written and presentation skills and business savvy in interpreting and applying data.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
