title: Derelle Kirksey # your name (or website title) here
logo: "/images/7AB2088F-81CE-4883-9C55-CC642D4ABE19-cropped.png?raw=true" # your photo (or logo) here
description:
  <br>
  Data Analyst and Automation Engineer based in San Diego, CA.
  <br>
  <br>
  Data analyst and engineering professional with experience at multiple large fast-paced public companies. Polished written and presentation skills and business savvy in interpreting and applying data. In-depth knowledge of relational databases, analytics, and business intelligence. 
  <br>
  <br>
  <div style="margin:auto">
    <a href=""><img src="images/google-plus.png?raw=true" width="30" height="30" /></a> 
    <a href="https://www.linkedin.com/in/derelle-kirksey-4535b211b/"><img src="images/linkedin2.png?raw=true" width="30" height="30"/></a> 
    <a href="https://github.com/CitizenSNPs><img src="images/github.png?raw=true" width="30" height="30"/></a> 
  </div>
  <br>
  <br>
  Resume
  <br>
  <span>
    <a href="./images/Derelle_Kirksey_Resume_2023_05_2.pdf" download="DPK_Resume.pdf">PDF</a>
    |
    <a href="/images/Derelle_Kirksey_Resume_2023_05_2.docx" download="DPK_Resume.docx">DOCX</a>
  </span>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
