title: Derelle Kirksey # your name (or website title) here
logo: "/images/DK-Symbol.png?raw=true" # your photo (or logo) here
description:
  <br>
  Data Analyst and Automation Engineer based in San Diego, CA.
  <br>
  <br>
  An experienced engineering professional with process design/improvement experience at a fast-paced public bio-technology company. 
  <br>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/derelle-kirksey-4535b211b/"><img src="images/linkedin.png?raw=true"/></a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
